# Copied from github.com/peterbourgon/diskv

language: erlang # wither art thou, Go?

install:
 - hg clone -r weekly https://code.google.com/p/go $HOME/go
 - cd $HOME/go/src && ./make.bash
 - mkdir -p $HOME/src || true
 - mkdir -p $HOME/bin || true
 - mkdir -p $HOME/pkg || true
 - export GOPATH=$HOME
 - export PATH=$PATH:$HOME/go/bin
 - ln -s $HOME/builds/tcard/functional $HOME/src/functional
 - go get -v github.com/tcard/functional

script:
 - cd $HOME/src/functional && go build -v .
 - cd $HOME/src/functional && go test -v .